name: CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'assets/'
      - 'dist/'
      - 'docs/'
      - 'sample-apps/'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
          - os: ubuntu-20.04
          - os: macos-10.15
          - os: macos-11
          - os: windows-2019
          - os: windows-2022

    continue-on-error: true

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Resolve dependencies (Ubuntu)
      run: |
        sudo apt-get update && \
        sudo apt-get install qt5-default qtwebengine5-dev
      if: contains(matrix.os, 'ubuntu')

    - name: Resolve dependencies (macOS and Windows)
      uses: jurplel/install-qt-action@v2
      with:
          modules: 'qtwebengine'
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'windows')

    - name: Build (Ubuntu and macOS)
      run: |
        qmake
        make -j
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')

    - name: Build (Windows)
      run: |
        qmake
        nmake
      if: contains(matrix.os, 'windows')
